### PR TITLE
Refactor Docker entrypoint

### PR DESCRIPTION
**Pull request by martialblog**
Hello,

I've refactored the Docker entrypoint to be more in-line with regular deployments. 

- This provides a setup which is more consistens with other Docker images (using environment variables)
 - Provides the possibility to deploy configuration files with configuration management tool
- Adds a bit more verbosity with log output

I also added the list of Environment Variables into the README.

Cheers, Markus

### CODE REVIEW

**Comment by bures** [comment]
Looks good. Thank you. 

Have you tested it with LDAP? To me it seems that the `ldapUidTag` settings may cause problems. In the existing version, the `uidTag` entry is placed in the config only if the `ldapUidTag` is set. At this moment, however, it is always included, albeit empty.

**Comment by martialblog** [comment]
I'll have a look at it and test it with an LDAP server

**Comment by bures** [comment]
Thank you.

**Comment by martialblog** [comment]
Hi, so I tested the config. Worked as expected.

If not present, the server/config/production.yaml gets initialized first with everything but the LDAP settings. Then this check kicks in:

```
    # Manage LDAP if enabled
    if [ "$WITH_LDAP" = "true" ]; then
        echo 'Info: LDAP enabled'
    cat >> server/config/production.yaml <<EOT
    ldap:
      enabled: true
      host: $LDAP_HOST
      port: $LDAP_PORT
      secure: $LDAP_SECURE
      bindUser: $LDAP_BIND_USER
      bindPasswort: $LDAP_BIND_PASS
      filter: $LDAP_FILTER
      baseDN: $LDAP_BASEDN
      uidTag: $LDAP_UIDTAG
EOT
    else
        echo 'Info: LDAP not enabled'
    cat >> server/config/production.yaml <<EOT
    ldap:
      enabled: false
EOT
```
If LDAP is disabled, application starts without having requiring futher settings.

**Comment by bures** [comment]
Perfect. May I please ask you for one more thing? Since this changes how the docker containers are to be used and since some people may already rely on it, can we at least issue some warning from docker-entrypoint.sh when MAILTRAIN_SETTING variable is present? Also, it would be good to have an example how to invoke docker with the env. variables in the README.md. Thanks.

**Comment by martialblog** [comment]
That's a good idea. You think just a warning is enough or should the entrypoint stop when it's present?

**Comment by martialblog** [comment]
Soft Warning
```
if [ ! -z "$MAILTRAIN_SETTING" ]; then
    echo 'Warning: MAILTRAIN_SETTINGS is no longer supported. See README'
fi
```

Hard version:
```
if [ ! -z "$MAILTRAIN_SETTING" ]; then
    echo 'Error: MAILTRAIN_SETTINGS is no longer supported. See README'
    exit 1
fi
```

**Comment by bures** [comment]
I think the hard version is better. I believe that when something fails, 
it's better if it fails hard. Easier to debug. Thanks.
T.

------ Original Message ------

**Comment by martialblog** [comment]
Alright. I just pushed the changes.

**Comment by bures** [comment]
Great. Thanks.

**Comment by gerhardsletten** [comment]
@martialblog After this change it looks like that to pass env-vars into the container you will need to create a `docker-compose.override.yml` that extend the mailtrains config enable own override of env-vars for either a `.env` file or as env-vars prepended to the docker-compose up command? 

```
version: '3'

services:
  mysql:
    command: mysqld --sql_mode=""
  mailtrain:
    environment:
    - URL_BASE_TRUSTED
    - URL_BASE_SANDBOX
    - URL_BASE_PUBLIC
    - WWW_PROXY
```
[Ref docker-compose doc about env-vars here](https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers)

Before this change you could just add all settings in the same into the docker-compose up, but if you just replace MAILTRAIN_SETTINGS with single options they will not be picked up in docker-entrypoint.sh

```
MAILTRAIN_SETTINGS="--trustedUrlBase https://mailtrain.example.com --sandboxUrlBase https://sbox.mailtrain.example.com --publicUrlBase https://lists.example.com --withProxy" docker-compose up
```
Maybe this should be explained in the README.md?

**Pull request merged**
