### PR TITLE
Add blacklist function

### PR DESCRIPTION
**Pull request by larrabee**
Hello. This PR add global blacklist function. Emails listed in this list will never receive emails.
Screenshots:
[API page](https://ibb.co/n0z085)
[Blacklist page](https://ibb.co/gwYSo5)
[Subscriber page](https://ibb.co/eYDSo5)

### CODE REVIEW

**Comment by andris9** [comment]
LGTM.

Its a large change, so I'll keep it open for a day, just in case. If there are no objections by then, then I'll merge it.

**Comment by larrabee** [comment]
Addition screenshots:
[Campaign status page](https://ibb.co/jF48T5)
[Blacklisted detail](https://ibb.co/ihhHMQ)

**Comment by larrabee** [comment]
Hello. Time to merge?;)

**Comment by andris9** [comment]
Yeah, sorry, forgot

**Comment by Arkni** [comment]
Hi there!

With this commit merged, I got the following error when trying to run `mailtrain` locally:
```
info Using local auth 
--> ComQueryPacket
ComQueryPacket { command: 3, sql: 'SHOW TABLES' }

--> ComQueryPacket
ComQueryPacket {
  command: 3,
  sql: 'SELECT `value` FROM `settings` WHERE `key`=\'db_schema_version\'' }

--> ComQueryPacket
ComQueryPacket {
  command: 3,
  sql: '# Header section\n# Define incrementing schema version number\nSET @schema_version = \'25\';\n\n# Create table to store global blacklist\nCREATE TABLE `blacklist` (\n  `email` varchar(255) NOT NULL,\n  PRIMARY KEY (`email`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n\n#Alter table campaigns\nALTER TABLE `campaigns` ADD COLUMN `blacklisted` int(11) unsigned NOT NULL DEFAULT \'0\' AFTER `delivered`;\n\n# Footer section\nLOCK TABLES `settings` WRITE;\nINSERT INTO `settings` (`key`, `value`) VALUES(\'db_schema_version\', @schema_version) ON DUPLICATE KEY UPDATE `value`=@schema_version;\nUNLOCK TABLES;\n' }

ERR! DB ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
```

I had to revert the last two commits to get it to work.

By the way, I'm using `mysql` version `5.6.21`.

**Comment by larrabee** [comment]
@Arkni Thank you for report. I create [PR](https://github.com/Mailtrain-org/mailtrain/pull/204) with bugfix. Can u try fixed version?

**Comment by Arkni** [comment]
@larrabee 
I confirm it's working.

Thanks a lot for the fast fix :)

**Comment by robertdebret** [comment]
Hi, anyway to upload the list of blacklisted recipients?
Any idea how to change the one by one feature to an upload list feature or a copy paste of emails on new line?

I am so new to node.js, have no clue how to change the add blacklisted users function to add multiple in one go.

Thank you for helping

**Pull request merged**
