### PR TITLE
Separate disable opened/clicked tracker to 2 options

### PR DESCRIPTION
**Pull request by larrabee**
Hello.
This PR separate disable opened/clicked tracker to 2 options. This useful when you want to track email opens, but don't want use links with redirects (links to Play Market / App Store not work with redirects on mobile devices).
Screenshot: http://imgur.com/a/lY7r2

### CODE REVIEW

**Comment by witzig** [comment]
@larrabee, could you add your git email to github, so your commits get properly linked and attributed? Thanks.

@andris9, @bures, looks good to me.

**Comment by bures** [comment]
I didn't test it. I briefly checked the code. It seems fine to me. No objections.

**Comment by larrabee** [comment]
@witzig Done.

**Comment by witzig** [comment]
Tested. Works fine. Thanks @larrabee.

**Pull request merged**
