### PR TITLE
API Improvements (v2)

### LINKED ISSUE #903: GET /lists/:email should return unsubscribed
Hello,
I want to know through API if an email has unsubscribed but it seems impossible for now.
Could we add this feature ?
Sincerely.

### PR DESCRIPTION
**Pull request by joker-x**
- Fix #903 #778 
- Working on #925

### CODE REVIEW

**Comment by bures** [comment]
Sounds good to me. There will be probably some changes once the implementation starts, but overall looks good. Eventually I would like to end up with removing api v1 and keeping api v2, so I'm still thinking how should we name the endpoints.  Since we are still in beta and your changes in the PR break the v1 API anyway (at least as far as I understood them), maybe we can just require a parameter in the reqeust header that specifies the version of the API. Default will be 2. Then we can keep the endpoints as `api/....`. What do you think? Thanks.

**Comment by bures** [comment]
Or even better, we have no default for the version. That means that if the version is not specified, and error will be throws. This would mitigate any problems where the endpoint has the same URL but does something slightly different than before.

**Comment by joker-x** [comment]
This PR don't break the v1 API, only add new fields (cid and status) in response of /list/:email endpoint. Also return cid instead of id in /unsubscribe/:listCid and /delete/:listCid endpoint, but with the user id can't be call to none of other api endpoint. The input params don't changed, only fixed in the documentation.

I think that insert version of the API in a query param will make difficult implement a new version from scratch. I would like all endpoints of v1 serve in route /api/v1/... and endpoints of v2 in /api/v2/..., but this break routes for v1. This is the reason for use /apiv2/... Maybe can use /api/... for v1 and /api/v2/... for v2

**Comment by joker-x** [comment]
I think that we must create documentation page of new api (including params and responses) after begin implementation to minimize breaking changes.

**Comment by joker-x** [comment]
The main changes in draft of version 2 with respect to version 1, in addition to supporting the new entities that did not exist will be:

- Use verbs http as REST standard: GET for listing, POST for create, PUT for update and DELETE for delete.
- Use plurals in entities always, for simplicity.
- All entities that only make sense inside a list put into /apiv2/lists/:listCid...
- Unify /api/list/:email and /api/lists-by-namespace/:namespaceid into /apiv2/lists because are filter params
- Unify /api/subscribe/:listCid and /api/unsubscribe/:listCid into /apiv2/lists/:listCid/subscriptions because both are updates of its table subscription

**Comment by bures** [comment]
Is this PR really non breaking? The changes in api.js seemed to me that they change the interface/semantics. But I could be wrong.

As for the proposal, I'm not concerned much about breaking the original API by requiring an extra header. Alternatively, for some time, we can assume that no header with version selector means v1. The reason why I'm not very much a fan of `v2` in the path is that I would like to start with a clean slate and not to keep in the path the heritage of originally having two APIs. 

We can easily have two different API routers (for v1 and v2) and just decide between them based on the header parameter which will specify the version (and default to v1 for the time being). 

I like the idea with the V2 API page. Just as I said, I would like to go with the paths /api/xxxx and specify the version in the header. It will also allow us to accommodate breaking changes in the API later on.

Thanks.

**Comment by joker-x** [comment]
> Is this PR really non breaking? The changes in api.js seemed to me that they change the interface/semantics. But I could be wrong.
> 

For practical purposes for the cases of unsubscribe and delete it is irrelevant that they return the cid instead of the id because the subscribers are identified by the email, no other endpoint receives the id or the cid. I have changed them for consistency since subscribe returned the cid.

Changes in /list/:email do matter: it was impossible to show which lists you were subscribed the API alone. Anyway, it also returns the previous fields with the same name, so whoever uses will continue to work for them.

The rest of the changes if I am not wrong are in the API documentation (still working on it).

> As for the proposal, I'm not concerned much about breaking the original API by requiring an extra header. Alternatively, for some time, we can assume that no header with version selector means v1. The reason why I'm not very much a fan of `v2` in the path is that I would like to start with a clean slate and not to keep in the path the heritage of originally having two APIs.
> 
> We can easily have two different API routers (for v1 and v2) and just decide between them based on the header parameter which will specify the version (and default to v1 for the time being).
> 

Ok, i already edited the draft https://github.com/Mailtrain-org/mailtrain/pull/935#issuecomment-678628497

> I like the idea with the V2 API page. Just as I said, I would like to go with the paths /api/xxxx and specify the version in the header. It will also allow us to accommodate breaking changes in the API later on.

If you could upload a skeleton with the routes, which processes the request header, a blank page for APIv2.js and an example of using curl with request header, I'll fill it in.

**Comment by bures** [comment]
Perfect. Thanks. Let's move the new API to a separate issue. I'll provide the routes and the request header with the curl example later today or tomorrow.

**Pull request merged**
