### PR TITLE
Add API support for GET /api/subscriptions/:listId

### PR DESCRIPTION
**Pull request by gkrol-zermelo**
I needed a way to retrieve all subscriptions to a list, in order to synchronize mailtrain with our own administration. I'm not that happy with the fact custom fields get weird generated names in the JSON, but in practice it's not a problem as those are easily copy-pasted into any code that uses them.

### CODE REVIEW

**Comment by afilp** [comment]
Hello, can this be merged please? It seems to be OK, thanks!

**Comment by witzig** [comment]
Thanks @gkrol-zermelo !

**Comment by afilp** [comment]
@witzig I feel a little strange too that there is a random naming in the names of custom fields.

**Comment by gkrol-zermelo** [comment]
I found this branch, which does seem to have nicer names for the custom fields: https://github.com/afanjul/mailtrain
We might be able to borrow some code from there.

**Comment by afanjul** [comment]
Didn't I do a pull request of that feature? I thought I did, but anyway if you need that I do a pull request for some commit, just paste here a link to the commit... (sorry im so busy these days)

**Pull request merged**
