### PR TITLE
[WIP] Added two parameters for ldap : method and nameTag

### PR DESCRIPTION
**Pull request by GuillaumeRemyCSI**

### CODE REVIEW

**Comment by bures** [comment]
I'm afraid that in the meantime we refactored the docker-entrypoint.sh - see PR #783. Please, could you update this PR to use the new way of passing the parameters (via environment variables)? I'll be than happy to merge it.
Thank you.

**Comment by martialblog** [comment]
@GuillaumeRemyCSI Hi, you can checkout the changes required here: https://github.com/martialblog/mailtrain/tree/ldap-parameters

**Comment by GuillaumeRemyCSI** [comment]
Thank you @bures and @martialblog, I'll work on it next week

**Comment by bures** [comment]
Perfect. Thanks.

**Pull request closed without merging**
