### PR TITLE
feat(api): Transactional mail rest api

### PR DESCRIPTION
**Pull request by goooseman**
In this PR we've added an API endpoint to send any email template with any template parameters to any email addresses.

This is really handy to use mailtrain as a transactional email sending system.

### CODE REVIEW

**Comment by goooseman** [comment]
Resolves #352

**Comment by bures** [comment]
Thank you. I had a quick look. Looks good. However, before accepting the PR, I would like to kindly ask you if you could add the following two things to make it in line with the rest of the API and general Mailtrain strategy:

1) Please use the context of the user (obtained via `req.context`) instead of `getAdminContext`, such that we can have granular permissions also for this API endpoint.

2) Please add an optional send configuration ID parameter to the API. Generally the `system` send configuration should be used only for delivering password reminders, etc. Having the ability to choose the send configuration makes it possible to differentiate sender domains, etc.

Thanks.

**Comment by alexeychikk** [comment]
@bures Done. Please take a look.

**Comment by bures** [comment]
Looks good. One more question and one more small request:

1) Do we use the instance of the TemplateSender class more than once? It makes sense for the CampaignSender because there it is created once and then send is invoked multiple times. I'm wondering whether to have TemplateSender as a class isn't a bit overkill. However, no big problem, especially if you think it makes sense to send through the object multiple times.

2) It would be good if the tag replacement could handle also fallbacks, such that we use the same syntax in templates for both transactional and mass sending. See https://github.com/Mailtrain-org/mailtrain/blob/3b20ac5ce710ddeb9ceef7a5afc2195b0a8fd399/server/lib/tools.js#L176

Thanks a lot.

**Comment by alexeychikk** [comment]
@bures 
> 1. Do we use the instance of the TemplateSender class more than once?
No, but just in case I've refactored it a bit more for possible future cases. So now class instance is useful when you want to have some shared (default) options across different send calls.
> 2. I've changed `lib/tools.js` a bit so now TemplateSender uses the same format logic as CampaignSender.

**Comment by bures** [comment]
Perfect! Thanks a lot.

**Comment by patchthecode** [comment]
Is there any documentation on how this works?

**Pull request merged**
