### PR TITLE
Update message-sender.js

### PR DESCRIPTION
**Pull request by ganeshkrishnan1**
catch null pointer exception. the regex returns null and crashes the whole system. also it resolves other "cannot replace" bugs raised here

### CODE REVIEW

**Comment by bures** [comment]
What are the steps to reproduce the error that is supposed to be fixed by this patch?

**Comment by ganeshkrishnan1** [comment]
For it it was a combination of these
1) Inline image with the [ bracket
2) Tags and unsubscribe tags
3) Click on "Convert to text" below to convert the rich text to plain text automatically (weirdly some tags are double bracketed)

Send the campaigns. Either the raw base64 image or the double brackets is triggering the null pointers

**Comment by bures** [comment]
That seems strange. In my view, your patch is just masking an error that might even originate somewhere else. I would rather get understanding of the error and why it arises when you click "Convert to text".

**Comment by bures** [comment]
I'm closing this due to inactivity. If you want to reopen this, please feel free. Thanks.

**Pull request closed without merging**
