### PR TITLE
Bugs and added features

### PR DESCRIPTION
**Pull request by Charlo270398**
Hello, I have fixed some bugs and added features. You can depreciate the initial commit "works" (I needed it to run Mailtrain on my own computer).

### CODE REVIEW

**Comment by bures** [comment]
Excellent. I'll take a look at it.

**Comment by bures** [comment]
Thanks.

**Comment by bures** [comment]
I'm merging this PR and polishing the code. However, I don't fully understand the idea behind the "Work with campaign's namespace". In my view, the namespace selection should be somewhere in the top-right corner and it should apply to everything (not just campaigns). 

Thus, I took over the features that pertain to visibility of user settings, the confirmation dialog for send, the adjustment of position of the "Overrride" boxes, etc. However, I left out the namespace filtering. 

Please check - https://github.com/Mailtrain-org/mailtrain/tree/development-pr-564

If that work, I'll merge it to deployment. Also, if you like to implement the universal namespace filter (i.e. the one in the top-right corner or so), I would appreciate it. In that case, please base it on the development-pr-564 branch.

Thanks.

**Comment by priethor** [comment]
> However, I don't fully understand the idea behind the "Work with campaign's namespace". In my view, the namespace selection should be somewhere in the top-right corner and it should apply to everything (not just campaigns).

The idea is to be able to filter, appart from with the top right global filtering as talked in #543, send configurations and/or lists to show only those the campaign has access to, always according to its namespace (see #563) in order to avoid misconfiguration. In this PR, the most granular option is implemented, which is probably too atomic, but always as a starting point for #563 and awaiting your input.

**Comment by bures** [comment]
I see. A bit of the problem is that you cannot say whether the campaign has access to the list, send-configuration, etc. unless you have a particular user. The reason for that is that you can individually share an entity (i.e. list, send-configuration, etc.) with someone. They don't have to be in the same namespace or whatever.

Also, I would rather keep the UX rule that whatever fields are shown in the entity settings, they somehow reflect what is persisted in the DB. The checkboxes for freezing the namespace are just view filter. As such, they should be kept somehow separate from the settings panel. I could even imagine that this could be another option in the right-hand corner. 

We could have options like:
- show only entities (including namespaces) only from a particular namespace and its children
- show only entities (including namespaces) only from user's namespace and its children
  - in this respect we could also introduce to a user a checkbox to automatically pre-select this option

Plus we could have a checkbox somewhere in the dropdown from this top-right namespace selector where we offer a checkbox "In entity settings, filter dependent entities by the main entity". This would have the same semantics as what you introduced to campaign settings, only it would be placed as part of the entity filtering control (where I believe it belongs).

What do you think please?

And please, let me tell you I really appreciate your readiness to contribute.

**Comment by bures** [comment]
BTW, I merged the cleaned up PR in the development branch. I have also fixed line endings of some older files (so that we have on LF in git). Please, if you continue on this, checkout the development branch and build it on top of it. I'll delete the development-pr-564 branch now.

**Pull request closed without merging**
