### PR TITLE
Fix import of date and general handle of mysql-dates in docker

### PR DESCRIPTION
**Pull request by gerhardsletten**
Need to parse the fields settings to make the date-format available in parsing, and set sql_mode in docker to make dates work even if they are not strict mysql-dates

### CODE REVIEW

**Comment by bures** [comment]
Thank you. Why is the sql-mode overridden in the docker?

**Comment by gerhardsletten** [comment]
@bures The background is that custom date-fields dont work, at least for european dates, which I think is  think has to do with the way dates are passed to the db. When they are stored from import of directly from an input not in the strict format which mysql docker image is configured with.

The background is that we have a list where we have a custom field with the customers last shopping date, and then we filter out recent customer from email campaigns, and it was in the csv-import I discovered that this was not working in the v2 branch.

There is also a discussion here  #748 and a link to a [SO tread here](https://stackoverflow.com/questions/44304777/er-truncated-wrong-value-incorrect-datetime-value)

**Comment by bures** [comment]
Please see my comment in #748.

**Comment by bures** [comment]
I'm closing this due to inactivity. If you want to reopen this, please feel free. Thanks.

**Pull request closed without merging**
