### PR TITLE
Attempt to better explain WWW_* env variables.

### PR DESCRIPTION
**Pull request by jeff-h**
This adds some examples for three of the env variables, which would hopefully make their intent clearer. If you're not keen on putting examples on just a few of the entries in this table, I'm happy to have another go, replacing these additions with a sentence underneath the ENV variables table.

### CODE REVIEW

**Review by jonathanmmm — APPROVED** [review]
seems good

**Review by jonathanmmm — CHANGES_REQUESTED** [review]
Remove lines 241-243

**Comment by bures** [comment]
Thanks.

**Comment by jonathanmmm** [comment]
> Remove lines 241-243

@bures could you remove the line 241-243? I approved to early, made a change suggestion.
Think they should be not in there.

**Comment by bures** [comment]
Could you submit a PR that I could merge?

**Comment by jonathanmmm** [comment]
> Could you submit a PR that I could merge?

@bures done: https://github.com/Mailtrain-org/mailtrain/pull/1181

**Pull request merged**
