### PR TITLE
Postfixbounce docker env

### PR DESCRIPTION
**Pull request by jonathanmmm**
Include postfixBounce ENVs and explaination into table of REAMDE.md

### CODE REVIEW

**Comment by bures** [comment]
Looks good. Is it finished? Ready for merge? Thanks.

**Comment by jonathanmmm** [comment]
@bures Yes, worked locally for me, bounces are recognized in mailtrain.

I could somewhere in the wiki also how to get the logging of postfix-mailcow.

Also wiki should be updated, as their is this [] brackets and `nc localhost 5699 -`, this dash makes problems with me (debian).
Haven't changed both (still the dash and don't know how to create a pull request/or change the wiki).

**Comment by bures** [comment]
Thanks. Regarding the wiki, it should have this repo: https://github.com/Mailtrain-org/mailtrain.wiki.git

**Comment by bures** [comment]
Anyway, I relaxed the restriction on editing the wiki. So maybe you are able to edit it directly now.

**Comment by jonathanmmm** [comment]
> Thanks. Regarding the wiki, it should have this repo: https://github.com/Mailtrain-org/mailtrain.wiki.git

@bures I updated the wiki, but the link to the repo is dead.

https://github.com/Mailtrain-org/mailtrain/wiki/Processing-bounces-with-Postfix

**Comment by bures** [comment]
Thanks.

**Pull request merged**
